services:
  backend: # Web API service
    container_name: lectornet-webapi
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - lectornetwork
    restart: on-failure
    
  frontend: # Blazor server service
    container_name: lectornet-blazorapp
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "1234:80"
    depends_on:
      - backend
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - lectornetwork

  sqlserver: # SQL database service
    container_name: sqlserver-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pass123@@"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - lectornetwork
    restart: always
    
networks:
  lectornetwork:

volumes:
  sqlvolume: