version: '3.8'

services:
  backend: # Web API service
    container_name: lector-net-web-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - lectornetwork
    restart: on-failure

  sqlserver: # SQL database service
    container_name: sqlserver-container
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pass123@@"
    ports:
      - "1401:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - lectornetwork
    restart: always
    
networks:
  lectornetwork:

volumes:
  sqlvolume: